repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: tag-env-sustainability

  # A short description of the repository that will show up on GitHub
  description: ğŸŒ³ğŸŒâ™»ï¸ TAG Environmental Sustainability 

  # A URL with more information about the repository
  homepage: https://sustainability.cncf.io/
