repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: wg-env-sustainability

  # A short description of the repository that will show up on GitHub
  description: üå≥üåç‚ôªÔ∏è Environmental Sustainability Working Group 

  # A URL with more information about the repository
  homepage: https://cncf.io/projects
  
  # Collaborators: give specific users access to this repository.
  # Note: changing this file will update the users visible in Github UI 
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # admin: CNCF staff
  - username: caniszczyk
    permission: admin

  - username: amye
    permission: admin
  
  # maintain: Bootstrap group volunteers prior to governance voting
  # Alphabetically

  - username: catblade
    permission: maintain

  - username: cdeliaRH
    permission: maintain

  - username: nikimanoledaki
    permission: maintain

  - username: mkorbi
    permission: maintain
    
  - username: scottrigby
    permission: maintain

